### ISSUE TITLE
Adding libraries to the project

### ISSUE THREAD

**Issue by shivams** [nrobinson2000/neopo#7]
In `po-util`, we had the `po lib` subcommand for downloading, adding and removing libraries from a project. Are there any similar commands in `neopo`?

**Comment by nrobinson2000** [comment]
I haven’t added library commands to neopo since the official library management system is now much better than it was when I was first developing po-util. When libraries 2.0 was released, I updated the `lib` commands to additionally serve as wrappers for Particle CLI which added some convenience but mostly bloated the utility.

Since neopo uses the same project structure as Workbench and Particle CLI, you can use Particle CLI to add libraries, which is similar to how po-util or Workbench add libraries.
[To search for a library](https://docs.particle.io/reference/developer-tools/cli/#particle-library-search) you can use:

```
particle library search
```

[To locally add a library to a project](https://docs.particle.io/reference/developer-tools/cli/#particle-library-copy) you can use:

```
particle library copy
```

**Comment by shivams** [comment]
Okay. Thank you. I see this now integrates really well with the existing Particle toolkit. :+1:
